import React, { FunctionComponent } from "react";
import Head from "next/head";

const Header: FunctionComponent = () => {
  return (
    <div>
      <Head>
        <title>Spotify-Clon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </div>
  );
};

export default Header;
